version: '3'

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - djangomysql
  djangomysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'birc'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'QSFCqgA8em$#B6Q@'
      MYSQL_ROOT_PASSWORD: 'QSFCqgA8em$#B6Q@'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
