version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: QSFCqgA8em$#B6Q@
      MYSQL_DATABASE: birc
      MYSQL_USER: admin
      MYSQL_PASSWORD: QSFCqgA8em$#B6Q@
