# Generated by Django 4.2.6 on 2023-10-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_norm', models.IntegerField()),
                ('start_date', models.DateField()),
                ('late_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.CharField(default='null', max_length=45, primary_key=True, serialize=False)),
                ('line_uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=5)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='sign',
            fields=[
                ('sing_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=None)),
                ('check_in_time', models.TimeField(default=None)),
                ('check_out_time', models.TimeField(default=None)),
                ('affair', models.TextField(default='')),
                ('hours', models.IntegerField()),
                ('isLate', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='notify',
            fields=[
                ('notify_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('create_time', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('create_time', models.DateTimeField()),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotApp.sign')),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotApp.student')),
            ],
        ),
    ]
