# Generated by Django 4.2.6 on 2023-11-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0002_alter_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='check_out_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
