# Generated by Django 4.2.6 on 2023-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0003_alter_sign_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='affair',
            field=models.TextField(default='', null=True),
        ),
    ]
