# Generated by Django 4.2.6 on 2023-11-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0004_alter_sign_affair'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='sing_id',
            new_name='sign_id',
        ),
    ]
