# Generated by Django 4.2.6 on 2023-11-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0005_rename_sing_id_sign_sign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='start_date',
        ),
    ]
