# Generated by Django 4.2.6 on 2023-11-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0006_remove_setting_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='hours',
            field=models.FloatField(),
        ),
    ]
