# Generated by Django 4.2.6 on 2023-12-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotApp', '0007_alter_sign_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='card_captcha',
            fields=[
                ('captcha_sno', models.AutoField(primary_key=True, serialize=False)),
                ('code_value', models.CharField(editable=False, max_length=5, unique=True)),
                ('expiry_time', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iotApp.student')),
            ],
        ),
    ]
